server {
    listen 80;

    location /empresas {
        proxy_pass http://empresas_app;
    }

    location /alumnos {
        proxy_pass http://alumnos_app;
    }

    location /admin {
        proxy_pass http://admin_app;
    }
}